import Head from "next/head";
import Contents from "../components/Contents";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Navbar */}
      <Navbar />

      {/* Content */}
      <Contents results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  );
  // .then((res) => res.json());
  const res = await request.json();

  return {
    props: {
      results: res.results,
    },
  };
}
